# your_orm/migrations/cli.py

import click
from alembic import command
from alembic.util import CommandError
from .config import (
    _get_config,
    _generate_files,
    _resolve_layout,
    _persist_pyproject_config,
    get_alembic_config,
    DB_OBJECT_NAME,
    load_template,
)
from your_orm.exceptions import ConfigurationError

# 1. Main CLI group
@click.group()
def cli():
    """The main entry point for the your-orm CLI."""
    pass

# 2. New top-level 'init' command
@cli.command()
@click.option(
    "--dir",
    "orm_dir",
    default=None,
    help="Override the target directory for database/migrations/models (defaults to db/).",
)
def init(orm_dir):
    """Initializes a complete, opinionated database structure."""
    click.echo("-> Initializing complete database structure...")
    try:
        project_root, config = _get_config(override_dir=orm_dir)
        relative_dir = config["your_orm_dir"]
        base_dir, migrations_dir, module_path = _resolve_layout(project_root, relative_dir)

        # --- Scaffolding logic ---

        base_dir.mkdir(parents=True, exist_ok=True)

        # Ensure parent directories are packages
        if base_dir != project_root:
            for p in base_dir.parents:
                if p == project_root:
                    break
                (p / "__init__.py").touch(exist_ok=True)

        (base_dir / "__init__.py").touch(exist_ok=True)

        # A. Scaffold migrations environment
        if not migrations_dir.exists():
            _generate_files(base_dir, module_path, DB_OBJECT_NAME)
            click.secho(f"✅ Created migration environment at: {migrations_dir}", fg="green")
        else:
            click.secho(f"Migration environment at {migrations_dir} already exists. Skipping.", fg="yellow")

        # B. Scaffold database.py and models directory
        db_file_path = base_dir / "database.py"
        if not db_file_path.exists():
            template = load_template("database.py.tpl")
            db_file_path.write_text(template)
            click.secho(f"✅ Created database entrypoint at: {db_file_path}", fg="green")
        else:
            click.secho(f"Database entrypoint at {db_file_path} already exists. Skipping.", fg="yellow")

        models_dir = db_file_path.parent / "models"
        models_dir.mkdir(exist_ok=True)
        (models_dir / "__init__.py").touch(exist_ok=True)
        click.secho(f"✅ Ensured models directory exists at: {models_dir}", fg="green")

        # Persist the resolved directory so future commands can infer it without flags.
        _persist_pyproject_config(project_root, relative_dir)

        click.secho("\nProject initialization complete!", fg="green")
        click.echo("Next steps:")
        click.echo(f"1. Define your models in the '{models_dir}' directory.")
        click.echo("2. Run 'your-orm migration create \"initial models\"' to create your first migration.")

    except Exception as e:
        click.secho(f"Error during initialization: {e}", fg="red", err=True)


# 3. 'migration' subcommand group
@cli.group(name="migration")
def migration_group():
    """Manages database schema migrations."""
    pass

# 4. Add existing commands to the 'migration' group
@migration_group.command()
@click.argument("message")
@click.option(
    "--dir",
    "orm_dir",
    default=None,
    help="Override the target directory (defaults to db/ or pyproject config).",
)
def create(message, orm_dir):
    """Creates a new migration file with autogenerated changes."""
    click.echo("-> Creating new migration...")
    try:
        alembic_cfg = get_alembic_config(override_dir=orm_dir)
        command.revision(alembic_cfg, message=message, autogenerate=True)
        click.secho("✅ New migration file created.", fg="green")
    except (CommandError, ConfigurationError) as e:
        click.secho(f"Error creating migration: {e}", fg="red")


@migration_group.command()
@click.argument("revision", default="head")
@click.option(
    "--dir",
    "orm_dir",
    default=None,
    help="Override the target directory (defaults to db/ or pyproject config).",
)
def upgrade(revision, orm_dir):
    """Applies migrations to the database."""
    click.echo(f"-> Applying migrations to revision: {revision}")
    try:
        alembic_cfg = get_alembic_config(override_dir=orm_dir)
        command.upgrade(alembic_cfg, revision)
        click.secho("✅ Migrations applied successfully.", fg="green")
    except (CommandError, ConfigurationError) as e:
        click.secho(f"Error applying migrations: {e}", fg="red")


@migration_group.command()
@click.argument("revision", default="-1")
@click.option(
    "--dir",
    "orm_dir",
    default=None,
    help="Override the target directory (defaults to db/ or pyproject config).",
)
def downgrade(revision, orm_dir):
    """Reverts migrations."""
    click.echo(f"-> Downgrading migrations to revision: {revision}")
    try:
        alembic_cfg = get_alembic_config(override_dir=orm_dir)
        command.downgrade(alembic_cfg, revision)
        click.secho("✅ Migrations reverted successfully.", fg="green")
    except (CommandError, ConfigurationError) as e:
        click.secho(f"Error reverting migrations: {e}", fg="red")


@migration_group.command()
@click.option(
    "--dir",
    "orm_dir",
    default=None,
    help="Override the target directory (defaults to db/ or pyproject config).",
)
def history(orm_dir):
    """Shows the migration history."""
    try:
        alembic_cfg = get_alembic_config(override_dir=orm_dir)
        command.history(alembic_cfg)
    except (CommandError, ConfigurationError) as e:
        click.secho(f"Error showing history: {e}", fg="red")
