# your_orm/migrations/cli.py

import click
from alembic import command
from alembic.util import CommandError
from pathlib import Path

from .config import _get_config, _generate_files, get_alembic_config
from your_orm.exceptions import ConfigurationError

# --- Template for the generated database.py file ---
DATABASE_TEMPLATE = """
# This file was generated by 'your-orm init'
# This is the single source of truth for your database connection.

from your_orm import Database

# 1. Create your Database instance
#    (Remember to set your database URL, e.g., from environment variables)
db = Database("sqlite+aiosqlite:///./app.db")

# 2. You can now import this 'db' object anywhere in your application
#    to define your models.
#
#    Example (in a models file):
#    from ..database import db
#    from your_orm import Mapped, mapped_column
#
#    class User(db.Model):
#        __tablename__ = "users"
#        id: Mapped[int] = mapped_column(primary_key=True)
#        name: Mapped[str]
"""

MODELS_INIT_TEMPLATE = '''"""
Convenience re-exports for your ORM models.

Example:
    from .user import User
    __all__ = ["User"]
"""

# Re-export your models here:
# from .user import User
# __all__ = ["User"]
'''

# 1. Main CLI group
@click.group()
def cli():
    """The main entry point for the your-orm CLI."""
    pass

# 2. New top-level 'init' command
@cli.command()
@click.option(
    "--stub-models-init/--no-stub-models-init",
    default=False,
    help="If enabled, seed models/__init__.py with sample re-export boilerplate.",
)
def init(stub_models_init):
    """Initializes a complete, opinionated database structure."""
    click.echo("-> Initializing complete database structure...")
    try:
        project_root, config = _get_config()
        db_object_path = config["db_object_path"]
        migrations_dir = (project_root / config["migrations_dir"]).resolve()

        # --- Scaffolding logic ---

        # A. Scaffold migrations environment
        if not migrations_dir.exists():
            _generate_files(migrations_dir, db_object_path)
            click.secho(f"✅ Created migration environment at: {migrations_dir}", fg="green")
        else:
            click.secho(f"Migration environment at {migrations_dir} already exists. Skipping.", fg="yellow")

        # B. Scaffold database.py and models directory
        parts = db_object_path.split('.')
        _ = parts.pop()  # obj_name ('db') is not needed for path
        filename = parts.pop() + ".py"

        dir_path = project_root
        if parts:
            dir_path = dir_path / Path(*parts)

        dir_path.mkdir(parents=True, exist_ok=True)

        # Ensure parent directories are packages
        # This creates __init__.py in my_app/ and my_app/db/
        if dir_path != project_root:
            for p in dir_path.parents:
                if p == project_root:
                    break
                (p / "__init__.py").touch(exist_ok=True)

        (dir_path / "__init__.py").touch(exist_ok=True)

        db_file_path = dir_path / filename
        if not db_file_path.exists():
            db_file_path.write_text(DATABASE_TEMPLATE)
            click.secho(f"✅ Created database entrypoint at: {db_file_path}", fg="green")
        else:
            click.secho(f"Database entrypoint at {db_file_path} already exists. Skipping.", fg="yellow")

        models_dir = db_file_path.parent / "models"
        models_dir.mkdir(exist_ok=True)
        models_init = models_dir / "__init__.py"
        if stub_models_init and not models_init.exists():
            models_init.write_text(MODELS_INIT_TEMPLATE)
            click.secho(f"✅ Stubbed re-export file at: {models_init}", fg="green")
        else:
            models_init.touch(exist_ok=True)
        click.secho(f"✅ Ensured models directory exists at: {models_dir}", fg="green")

        click.secho("\nProject initialization complete!", fg="green")
        click.echo("Next steps:")
        click.echo(f"1. Define your models in the '{models_dir}' directory.")
        click.echo("2. Run 'your-orm migrate create \"initial models\"' to create your first migration.")

    except Exception as e:
        click.secho(f"Error during initialization: {e}", fg="red", err=True)


# 3. 'migrate' subcommand group
@cli.group()
def migrate():
    """Manages database schema migrations."""
    pass

# 4. Add existing commands to the 'migrate' group
@migrate.command()
@click.argument("message")
def create(message):
    """Creates a new migration file with autogenerated changes."""
    click.echo("-> Creating new migration...")
    try:
        alembic_cfg = get_alembic_config()
        command.revision(alembic_cfg, message=message, autogenerate=True)
        click.secho("✅ New migration file created.", fg="green")
    except (CommandError, ConfigurationError) as e:
        click.secho(f"Error creating migration: {e}", fg="red")


@migrate.command()
@click.argument("revision", default="head")
def upgrade(revision):
    """Applies migrations to the database."""
    click.echo(f"-> Applying migrations to revision: {revision}")
    try:
        alembic_cfg = get_alembic_config()
        command.upgrade(alembic_cfg, revision)
        click.secho("✅ Migrations applied successfully.", fg="green")
    except (CommandError, ConfigurationError) as e:
        click.secho(f"Error applying migrations: {e}", fg="red")


@migrate.command()
@click.argument("revision", default="-1")
def downgrade(revision):
    """Reverts migrations."""
    click.echo(f"-> Downgrading migrations to revision: {revision}")
    try:
        alembic_cfg = get_alembic_config()
        command.downgrade(alembic_cfg, revision)
        click.secho("✅ Migrations reverted successfully.", fg="green")
    except (CommandError, ConfigurationError) as e:
        click.secho(f"Error reverting migrations: {e}", fg="red")


@migrate.command()
def history():
    """Shows the migration history."""
    try:
        alembic_cfg = get_alembic_config()
        command.history(alembic_cfg)
    except (CommandError, ConfigurationError) as e:
        click.secho(f"Error showing history: {e}", fg="red")
