# your_orm/migrations/cli.py

import click
from alembic import command
from alembic.util import CommandError
from pathlib import Path

from .config import _get_config, _generate_files, get_alembic_config
from your_orm.exceptions import ConfigurationError


@click.group()
def migrate():
    """A wrapper for the Alembic migration tool."""
    pass


@migrate.command()
def init():
    """Initializes a new, self-contained migration environment."""
    click.echo("-> Finding configuration...")
    try:
        config = _get_config()
        migrations_dir = Path(config["migrations_dir"])

        if migrations_dir.exists():
            click.secho(
                f"Directory '{migrations_dir}' already exists. Initialization skipped.",
                fg="yellow",
            )
            return

        click.echo(f"-> Creating migration environment at '{migrations_dir}'...")
        _generate_files(migrations_dir, config["db_object_path"])
        click.secho("✅ Migration environment initialized successfully.", fg="green")

    except (ConfigurationError, FileNotFoundError) as e:
        click.secho(f"Error: {e}", fg="red")


@migrate.command()
@click.argument("message")
def create(message):
    """Creates a new migration file with autogenerated changes."""
    click.echo("-> Creating new migration...")
    try:
        alembic_cfg = get_alembic_config()
        command.revision(alembic_cfg, message=message, autogenerate=True)
        click.secho("✅ New migration file created.", fg="green")
    except (CommandError, ConfigurationError) as e:
        click.secho(f"Error creating migration: {e}", fg="red")


@migrate.command()
@click.argument("revision", default="head")
def upgrade(revision):
    """Applies migrations to the database."""
    click.echo(f"-> Applying migrations to revision: {revision}")
    try:
        alembic_cfg = get_alembic_config()
        command.upgrade(alembic_cfg, revision)
        click.secho("✅ Migrations applied successfully.", fg="green")
    except (CommandError, ConfigurationError) as e:
        click.secho(f"Error applying migrations: {e}", fg="red")


@migrate.command()
@click.argument("revision", default="-1")
def downgrade(revision):
    """Reverts migrations."""
    click.echo(f"-> Downgrading migrations to revision: {revision}")
    try:
        alembic_cfg = get_alembic_config()
        command.downgrade(alembic_cfg, revision)
        click.secho("✅ Migrations reverted successfully.", fg="green")
    except (CommandError, ConfigurationError) as e:
        click.secho(f"Error reverting migrations: {e}", fg="red")


@migrate.command()
def history():
    """Shows the migration history."""
    try:
        alembic_cfg = get_alembic_config()
        command.history(alembic_cfg)
    except (CommandError, ConfigurationError) as e:
        click.secho(f"Error showing history: {e}", fg="red")