# duo_orm/basemodel.py

from __future__ import annotations
from datetime import datetime, timezone
import asyncio
from typing import TYPE_CHECKING, Any, Awaitable, Dict, Iterable, Optional, Sequence, Tuple, Type, TypeVar

from sqlalchemy import inspect as sa_inspect
from sqlalchemy.orm.exc import UnmappedInstanceError

from .query import QueryBuilder
from ._payloads import coerce_payload as _coerce_payload
from .executor import _save, _delete_instance, _create_bulk, _run_with_session
from .exceptions import ValidationError
from .session import active_session_var, is_async_context

if TYPE_CHECKING:
    from .db import Database

# This helps with type hinting for model instances.
T = TypeVar("T")


class _DuoOrmMethods:
    """
    A mixin providing the core Active Record-style API for DuoORM models.

    This class is not intended to be used directly by end-users. It is
    automatically mixed into the `db.Model` base class that is generated by
    each `Database` instance.
    """
    _db: "Database" = None
    """A class-level attribute linking the model back to its owning `Database` instance."""

    # --- Class-level Querying API ---

    @classmethod
    def _get_query_builder(cls: Type[T]) -> "QueryBuilder[T]":
        """Internal helper to create a QueryBuilder for this model."""
        return QueryBuilder(cls, db=cls._db)

    @classmethod
    def where(cls: Type[T], *args: Any) -> "QueryBuilder[T]":
        """
        Starts a query with a WHERE clause.

        This is the primary entry point for building queries.

        Args:
            *args: One or more SQLAlchemy filter expressions.

        Returns:
            A new `QueryBuilder` instance ready for chaining or execution.
        """
        return cls._get_query_builder().where(*args)

    @classmethod
    def all(cls: Type[T]) -> list[T] | Awaitable[list[T]]:
        """
        Fetches all records for this model.

        This is a convenience shortcut for `Model.where().all()`.

        Returns:
            A list of model instances (sync) or an awaitable that returns a list (async).
        """
        return cls._get_query_builder().all()

    @classmethod
    def count(cls: Type[T]) -> int | Awaitable[int]:
        """
        Counts all records for this model.

        Returns:
            The total row count (sync) or an awaitable resolving to the count (async).
        """
        return cls._get_query_builder().count()

    @classmethod
    def first(cls: Type[T]) -> Optional[T] | Awaitable[Optional[T]]:
        """
        Fetches the first record for this model.

        This is a convenience shortcut for `Model.where().first()`.

        Returns:
            A model instance or `None` (sync), or an awaitable that returns a
            model instance or `None` (async).
        """
        return cls._get_query_builder().first()

    @classmethod
    def related(cls: Type[T], relationship_attr, **kwargs: Dict[str, Any]) -> "QueryBuilder[T]":
        """
        Starts a query and configures eager loading for a relationship.

        This is the primary tool for solving the N+1 query problem.

        Args:
            relationship_attr: The model's relationship attribute (e.g., `User.posts`).
            **kwargs: Additional options passed to the `QueryBuilder.related` method,
                such as `loader`, `where`, or `aggregate`.

        Returns:
            A new `QueryBuilder` instance with eager loading configured.
        """
        return cls._get_query_builder().related(relationship_attr, **kwargs)

    @classmethod
    def order_by(cls: Type[T], *args: str, **kwargs: Dict[str, Any]) -> "QueryBuilder[T]":
        """
        Starts a query with an ORDER BY clause.

        Args:
            *args: Field names to order by. Prefix with `-` for descending order.

        Returns:
            A new `QueryBuilder` instance with ordering applied.
        """
        return cls._get_query_builder().order_by(*args, **kwargs)

    @classmethod
    def paginate(cls: Type[T], *args: Any, **kwargs: Dict[str, Any]) -> "QueryBuilder[T]":
        """
        Starts a query with pagination (LIMIT/OFFSET) applied.

        Args:
            limit (int): The number of records to return.
            offset (int, optional): The number of records to skip.

        Returns:
            A new `QueryBuilder` instance with pagination applied.
        """
        return cls._get_query_builder().paginate(*args, **kwargs)

    @classmethod
    def iterate(cls: Type[T], *args: Any, **kwargs: Dict[str, Any]):
        """
        Stream records (or batches) using QueryBuilder.iterate.

        Args:
            batch_size: size of each fetch batch (defaults to 200).
            batch: when True, yields lists of models; when False, yields one model at a time.
        """
        return cls._get_query_builder().iterate(*args, **kwargs)

    @classmethod
    def update_bulk(
        cls: Type[T],
        values: Dict[str, Any],
        *,
        with_hooks: bool = False,
        batch_size: int = 200,
        require_filter: bool = True,
        per_batch_transaction: bool = True,
    ) -> None | Awaitable[None]:
        """Convenience wrapper for QueryBuilder.update_bulk on the whole table or filtered query."""
        return cls.where().update_bulk(
            values,
            with_hooks=with_hooks,
            batch_size=batch_size,
            require_filter=require_filter,
            per_batch_transaction=per_batch_transaction,
        )

    @classmethod
    def delete_bulk(
        cls: Type[T],
        *,
        with_hooks: bool = False,
        batch_size: int = 200,
        require_filter: bool = True,
        per_batch_transaction: bool = True,
    ) -> None | Awaitable[None]:
        """Convenience wrapper for QueryBuilder.delete_bulk."""
        return cls.where().delete_bulk(
            with_hooks=with_hooks,
            batch_size=batch_size,
            require_filter=require_filter,
            per_batch_transaction=per_batch_transaction,
        )

    @classmethod
    def get(cls: Type[T], *pk_values: Any, **pk_kwargs: Any) -> Optional[T] | Awaitable[Optional[T]]:
        """
        Fetch a single record by primary key. Supports positional args for single PK
        or keyword args for composite keys (field names must match column keys).
        Returns `None` when not found.
        """
        mapper = sa_inspect(cls)
        pk_cols = list(mapper.primary_key)
        if not pk_cols:
            raise ValidationError(f"{cls.__name__} has no primary key defined.")

        filters = []
        if pk_kwargs:
            if len(pk_kwargs) != len(pk_cols):
                raise ValidationError("Number of primary key fields does not match model definition.")
            for col in pk_cols:
                if col.key not in pk_kwargs:
                    raise ValidationError(f"Missing primary key component '{col.key}'.")
                filters.append(col == pk_kwargs[col.key])
        else:
            if len(pk_cols) != 1:
                raise ValidationError("Provide keyword arguments for composite primary keys.")
            if len(pk_values) != 1:
                raise ValidationError("Exactly one positional primary key value is required.")
            filters.append(pk_cols[0] == pk_values[0])
        identity = tuple(pk_kwargs[col.key] for col in pk_cols) if pk_kwargs else (pk_values[0],)
        identity = identity[0] if len(identity) == 1 else identity

        # Use session.get to leverage the identity map when available.
        if is_async_context():
            async def _async_get():
                active = active_session_var.get(None)
                if active is not None:
                    return await active.get(cls, identity)
                db = cls._db
                async with db.async_session_factory() as session:
                    return await session.get(cls, identity)
            return _async_get()

        def _sync_get(session):
            return session.get(cls, identity)

        active = active_session_var.get(None)
        if active is not None:
            return _sync_get(active)
        db = cls._db
        with db.sync_session_factory() as session:
            return _sync_get(session)

    @classmethod
    def create(cls: Type[T], data: Dict[str, Any] | T = None, **kwargs: Any) -> T | Awaitable[T]:
        """
        Convenience classmethod to build and persist a new instance in one call.
        Accepts a dict or keyword args. Returns the saved instance.
        """
        if data is None:
            data = {}
        payload: Dict[str, Any]
        if isinstance(data, cls):
            instance: T = data
        else:
            payload = _coerce_payload(data, partial=False, model_cls=cls)
            payload.update(kwargs)
            instance = cls(**payload)  # type: ignore[arg-type]

        res = instance.save()
        if asyncio.iscoroutine(res):
            async def _awaited():
                await res
                return instance
            return _awaited()
        return instance

    @classmethod
    def create_bulk(
        cls: Type[T],
        rows: Sequence[Dict[str, Any] | T],
        *,
        with_hooks: bool = False,
        batch_size: int = 200,
        return_models: bool = False,
    ) -> None | list[T] | Awaitable[None] | Awaitable[list[T]]:
        """
        Bulk insert records. By default skips per-row hooks/validation for speed.
        Set `with_hooks=True` to run `validate()` and timestamp hooks on each row.
        """
        normalized: list[Dict[str, Any] | T] = []
        for row in rows:
            if isinstance(row, cls):
                normalized.append(row)
            else:
                normalized.append(_coerce_payload(row, partial=False, model_cls=cls))

        return _create_bulk(
            cls,
            normalized,
            with_hooks=with_hooks,
            batch_size=batch_size,
            return_models=return_models,
        )

    # --- Instance-level Actions ---

    def save(self: T) -> None | Awaitable[None]:
        """
        Saves the current instance to the database (INSERT for new, UPDATE for existing).

        This method automatically runs `.validate()` and applies timestamp hooks
        before persisting the object.
        """
        self.validate()
        try:
            state = sa_inspect(self)
            is_insert = state.transient or state.pending
        except UnmappedInstanceError:
            # The instance is not yet part of a session, so it must be an insert.
            is_insert = True
        self._apply_timestamp_hooks(is_insert=is_insert)
        return _save(self)

    def update(self: T, data: Dict[str, Any] | None = None, **kwargs: Any) -> None | Awaitable[None]:
        """
        Apply changes to the instance and persist them (hooks/validation run).
        """
        if data is not None:
            payload = _coerce_payload(data, partial=True, model_cls=self.__class__)
            for key, val in payload.items():
                setattr(self, key, val)
        for key, val in kwargs.items():
            setattr(self, key, val)
        return self.save()

    # --- Pydantic integration helpers ---

    @classmethod
    def from_schema(cls: Type[T], payload: Any) -> T:
        """Build an **unsaved** instance from a Pydantic model or dict."""
        data = _coerce_payload(payload, partial=False, model_cls=cls)
        return cls(**data)  # type: ignore[arg-type]

    def apply_schema(self: T, payload: Any) -> T:
        """
        Apply a Pydantic model or dict to this instance **without** saving.

        Partial updates are supported; missing/None fields are ignored.
        """
        data = _coerce_payload(payload, partial=True, model_cls=self.__class__)
        for key, val in data.items():
            setattr(self, key, val)
        return self

    def to_schema(self: T, schema_cls: Any) -> Any:
        """Serialize this instance into the provided Pydantic schema class."""
        if not hasattr(schema_cls, "model_validate"):
            raise ValidationError("Schema class must be a Pydantic BaseModel with model_validate().")
        # Require from_attributes for safe ORM serialization
        model_config = getattr(schema_cls, "model_config", None) or getattr(schema_cls, "Config", None)
        from_attr = False
        if isinstance(model_config, dict):
            from_attr = model_config.get("from_attributes", False)
        else:
            from_attr = getattr(model_config, "from_attributes", False)
        if not from_attr:
            raise ValidationError("Schema class must set model_config.from_attributes = True for ORM export.")
        try:
            return schema_cls.model_validate(self, from_attributes=True)
        except Exception as exc:  # pydantic.ValidationError or config issues
            raise ValidationError(str(exc)) from exc

    def delete(self: T) -> None | Awaitable[None]:
        """
        Deletes the current instance from the database.

        The operation is cascaded to related objects based on the relationship
        configuration (e.g., `cascade="all, delete-orphan"`).
        """
        return _delete_instance(self)

    # --- Developer Experience Helpers ---

    def validate(self: T) -> None:
        """
        Hook for subclasses to implement custom validation logic.

        This method is called automatically before `.save()` and `.create_bulk()`
        (when `with_hooks=True`). To block persistence, implementations of this
        method should raise a `ValidationError`.

        Raises:
            ValidationError: If the model's state is invalid.
        """
        return None

    @classmethod
    def fields(cls: Type[T]) -> Tuple[str, ...]:
        """
        Returns a tuple of all mapped column names for this model.

        Returns:
            A tuple of strings representing the model's field names.
        """
        mapper = sa_inspect(cls)
        return tuple(col.key for col in mapper.columns)

    def to_dict(self: T) -> Dict[str, Any]:
        """
        Serializes the instance's column values to a dictionary.

        This method only includes values from columns, not from relationships
        or other Python attributes.

        Returns:
            A dictionary mapping column names to their values.
        """
        mapper = sa_inspect(self.__class__)
        return {col.key: getattr(self, col.key) for col in mapper.columns}

    def _apply_timestamp_hooks(self: T, *, is_insert: bool) -> None:
        """Applies `set_on` semantics based on column info."""
        now = _utcnow()
        mapper = sa_inspect(self.__class__)
        for column in mapper.columns:
            info = getattr(column, "info", {}) or {}
            targets: set[str] = set()

            # For compatibility with other libraries, honor auto_now/auto_now_add
            if info.get("auto_now"):
                targets.update({"create", "update"})
            if info.get("auto_now_add"):
                targets.add("create")

            set_on = info.get("set_on")
            if set_on:
                targets.update(set_on if isinstance(set_on, Iterable) and not isinstance(set_on, str) else [set_on])

            if not targets:
                continue

            if "update" in targets:
                setattr(self, column.key, now)
            if is_insert and "create" in targets:
                setattr(self, column.key, now)
        return None


def _utcnow() -> datetime:
    """Returns the current time in UTC with timezone info."""
    return datetime.now(timezone.utc)
