# duo_orm/basemodel.py

from __future__ import annotations
from datetime import datetime, timezone
from typing import TYPE_CHECKING, TypeVar, Dict, Any, Iterable, Type

from sqlalchemy import inspect as sa_inspect
from sqlalchemy.orm.exc import UnmappedInstanceError

from .query import QueryBuilder
from .executor import _save, _delete_instance, _bulk_create
from .exceptions import ValidationError

if TYPE_CHECKING:
    from .db import Database

# This helps with type hinting for model instances.
T = TypeVar("T")


class _DuoOrmMethods:
    """
    A mixin providing the core Active Record-style API for DuoORM models.

    This class is not intended to be used directly by end-users. It is
    automatically mixed into the `db.Model` base class that is generated by
    each `Database` instance.
    """
    _db: "Database" = None
    """A class-level attribute linking the model back to its owning `Database` instance."""

    # --- Class-level Querying API ---

    @classmethod
    def _get_query_builder(cls: Type[T]) -> "QueryBuilder[T]":
        """Internal helper to create a QueryBuilder for this model."""
        return QueryBuilder(cls, db=cls._db)

    @classmethod
    def where(cls: Type[T], *args) -> "QueryBuilder[T]":
        """
        Starts a query with a WHERE clause.

        This is the primary entry point for building queries.

        Args:
            *args: One or more SQLAlchemy filter expressions.

        Returns:
            A new `QueryBuilder` instance ready for chaining or execution.
        """
        return cls._get_query_builder().where(*args)

    @classmethod
    def all(cls: Type[T]):
        """
        Fetches all records for this model.

        This is a convenience shortcut for `Model.where().all()`.

        Returns:
            A list of model instances (sync) or an awaitable that returns a list (async).
        """
        return cls._get_query_builder().all()

    @classmethod
    def first(cls: Type[T]):
        """
        Fetches the first record for this model.

        This is a convenience shortcut for `Model.where().first()`.

        Returns:
            A model instance or `None` (sync), or an awaitable that returns a
            model instance or `None` (async).
        """
        return cls._get_query_builder().first()

    @classmethod
    def related(cls: Type[T], relationship_attr, **kwargs) -> "QueryBuilder[T]":
        """
        Starts a query and configures eager loading for a relationship.

        This is the primary tool for solving the N+1 query problem.

        Args:
            relationship_attr: The model's relationship attribute (e.g., `User.posts`).
            **kwargs: Additional options passed to the `QueryBuilder.related` method,
                such as `loader`, `where`, or `aggregate`.

        Returns:
            A new `QueryBuilder` instance with eager loading configured.
        """
        return cls._get_query_builder().related(relationship_attr, **kwargs)

    @classmethod
    def order_by(cls: Type[T], *args, **kwargs) -> "QueryBuilder[T]":
        """
        Starts a query with an ORDER BY clause.

        Args:
            *args: Field names to order by. Prefix with `-` for descending order.

        Returns:
            A new `QueryBuilder` instance with ordering applied.
        """
        return cls._get_query_builder().order_by(*args, **kwargs)

    @classmethod
    def paginate(cls: Type[T], *args, **kwargs) -> "QueryBuilder[T]":
        """
        Starts a query with pagination (LIMIT/OFFSET) applied.

        Args:
            limit (int): The number of records to return.
            offset (int, optional): The number of records to skip.

        Returns:
            A new `QueryBuilder` instance with pagination applied.
        """
        return cls._get_query_builder().paginate(*args, **kwargs)

    @classmethod
    def bulk_create(cls: Type[T], instances: list[T]):
        """
        Performs a bulk insert of multiple model instances in a single transaction.

        This method first runs `.validate()` and applies timestamp hooks on all
        instances before sending them to the database. If any instance fails

        validation, the entire operation is aborted and nothing is saved.

        Args:
            instances: A list of new, unsaved model instances.
        """
        for instance in instances:
            instance.validate()
            instance._apply_timestamp_hooks(is_insert=True)
        return _bulk_create(cls, instances)

    # --- Instance-level Actions ---

    def save(self: T):
        """
        Saves the current instance to the database (INSERT for new, UPDATE for existing).

        This method automatically runs `.validate()` and applies timestamp hooks
        before persisting the object.
        """
        self.validate()
        try:
            state = sa_inspect(self)
            is_insert = state.transient or state.pending
        except UnmappedInstanceError:
            # The instance is not yet part of a session, so it must be an insert.
            is_insert = True
        self._apply_timestamp_hooks(is_insert=is_insert)
        return _save(self)

    def delete(self: T):
        """
        Deletes the current instance from the database.

        The operation is cascaded to related objects based on the relationship
        configuration (e.g., `cascade="all, delete-orphan"`).
        """
        return _delete_instance(self)

    # --- Developer Experience Helpers ---

    def validate(self: T):
        """
        Hook for subclasses to implement custom validation logic.

        This method is called automatically before `.save()` and `.bulk_create()`.
        To block persistence, implementations of this method should raise a
        `ValidationError`.

        Raises:
            ValidationError: If the model's state is invalid.
        """
        return None

    @classmethod
    def fields(cls: Type[T]) -> tuple[str, ...]:
        """
        Returns a tuple of all mapped column names for this model.

        Returns:
            A tuple of strings representing the model's field names.
        """
        mapper = sa_inspect(cls)
        return tuple(col.key for col in mapper.columns)

    def to_dict(self: T) -> Dict[str, Any]:
        """
        Serializes the instance's column values to a dictionary.

        This method only includes values from columns, not from relationships
        or other Python attributes.

        Returns:
            A dictionary mapping column names to their values.
        """
        mapper = sa_inspect(self.__class__)
        return {col.key: getattr(self, col.key) for col in mapper.columns}

    def _apply_timestamp_hooks(self: T, *, is_insert: bool):
        """Applies `set_on` semantics based on column info."""
        now = _utcnow()
        mapper = sa_inspect(self.__class__)
        for column in mapper.columns:
            info = getattr(column, "info", {}) or {}
            targets: set[str] = set()

            # For compatibility with other libraries, honor auto_now/auto_now_add
            if info.get("auto_now"):
                targets.update({"create", "update"})
            if info.get("auto_now_add"):
                targets.add("create")

            set_on = info.get("set_on")
            if set_on:
                targets.update(set_on if isinstance(set_on, Iterable) and not isinstance(set_on, str) else [set_on])

            if not targets:
                continue

            if "update" in targets:
                setattr(self, column.key, now)
            if is_insert and "create" in targets:
                setattr(self, column.key, now)
        return None


def _utcnow() -> datetime:
    """Returns the current time in UTC with timezone info."""
    return datetime.now(timezone.utc)
