# This file was generated by 'duo-orm init'
# This is the single source of truth for your database connection.

from duo_orm import Database

# 1. Create your Database instance
#    (Remember to set your database URL, e.g., from environment variables)
#    Use driverless URLs (e.g., sqlite:///./app.db, postgresql://..., mysql://..., mssql://..., oracle://...)
db = Database("sqlite:///./app.db")

# 2. You can now import this 'db' object anywhere in your application
#    to define your models.
#
#    Example (in a models file):
#    from ..database import db
#    from duo_orm import Mapped, mapped_column
#
#    class User(db.Model):
#        __tablename__ = "users"
#        id: Mapped[int] = mapped_column(primary_key=True)
#        name: Mapped[str]
