# your_orm/basemodel.py

from __future__ import annotations
from datetime import datetime, timezone
from typing import TYPE_CHECKING, TypeVar, Dict, Any, Iterable

from sqlalchemy import inspect as sa_inspect, DateTime
from sqlalchemy.orm import mapped_column

from .query import QueryBuilder
from .executor import _save, _delete_instance, _bulk_create
if TYPE_CHECKING:
    from .db import Database

# This helps with type hinting for model instances.
T = TypeVar("T")


class _YourOrmMethods:
    """
    A mixin class providing the Active Record-style API.

    This class is not intended to be used directly by the end-user. It will be
    mixed into the user-facing base model that is generated by the Database
    instance.
    """
    # This class attribute will be set by the Database class when it creates
    # the user-facing Model. This is the key that links the models back
    # to the configured database instance.
    _db: "Database" = None

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)

    # --- Class-level Querying API ---

    @classmethod
    def _get_query_builder(cls: T) -> "QueryBuilder[T]":
        """Internal helper to create a QueryBuilder for this model."""
        # The `cls._db` attribute provides the crucial link to the db instance.
        return QueryBuilder(cls, db=cls._db)

    @classmethod
    def where(cls: T, *args) -> "QueryBuilder[T]":
        """Starts a query with a WHERE clause."""
        return cls._get_query_builder().where(*args)

    @classmethod
    def all(cls: T):
        """Fetches all records for this model."""
        return cls._get_query_builder().all()

    @classmethod
    def first(cls: T):
        """Fetches the first record for this model."""
        return cls._get_query_builder().first()

    @classmethod
    def related(cls: T, relationship_attr, **kwargs) -> "QueryBuilder[T]":
        """Starts a query scoped by a relationship helper."""
        return cls._get_query_builder().related(relationship_attr, **kwargs)

    @classmethod
    def bulk_create(cls: T, instances: list[T]):
        """Performs a bulk insert of multiple model instances."""
        for instance in instances:
            instance.validate()
            instance._apply_timestamp_hooks(is_insert=True)
        return _bulk_create(cls, instances)

    # --- Instance-level Actions ---

    def save(self: T):
        """
        Saves the current instance to the database (INSERT or UPDATE).
        """
        self.validate()
        state = sa_inspect(self)
        is_insert = not state.persistent
        self._apply_timestamp_hooks(is_insert=is_insert)
        return _save(self)

    def delete(self: T, *, force: bool = False):
        """Deletes the current instance."""
        return _delete_instance(self)

    # --- Developer Experience Helpers ---

    def validate(self: T):
        """
        Hook for subclasses to implement custom validation.

        Raise ValidationError with an optional field/detail payload to block persistence.
        """
        return None

    @classmethod
    def fields(cls) -> tuple[str, ...]:
        """Returns the column names defined on this model."""
        mapper = sa_inspect(cls)
        return tuple(col.key for col in mapper.columns)

    def to_dict(self: T) -> Dict[str, Any]:
        """Serializes the instance to a plain dictionary of column values."""
        mapper = sa_inspect(self.__class__)
        return {col.key: getattr(self, col.key) for col in mapper.columns}

    def _apply_timestamp_hooks(self: T, *, is_insert: bool):
        """Applies Django-style auto_now/auto_now_add semantics based on column info."""
        now = _utcnow()
        mapper = sa_inspect(self.__class__)
        for column in mapper.columns:
            info = getattr(column, "info", {}) or {}
            targets: set[str] = set()

            if info.get("auto_now"):
                targets.update({"create", "update"})
            if info.get("auto_now_add"):
                targets.add("create")

            set_on = info.get("set_on")
            if set_on:
                if isinstance(set_on, str):
                    targets.add(set_on)
                elif isinstance(set_on, Iterable):
                    targets.update(str(value) for value in set_on)

            if not targets:
                continue

            if "update" in targets:
                setattr(self, column.key, now)
            if is_insert and "create" in targets:
                setattr(self, column.key, now)
        return None


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)
