# This is a managed alembic.ini file generated by your-orm.
# It points to the current directory as its home.
# The database URL is configured dynamically from your ORM setup.
[alembic]
script_location = .