# This file was generated by 'your-orm init'
# This is the single source of truth for your database connection.

from your_orm import Database

# 1. Create your Database instance
#    (Remember to set your database URL, e.g., from environment variables)
db = Database("sqlite+aiosqlite:///./app.db")

# 2. You can now import this 'db' object anywhere in your application
#    to define your models.
#
#    Example (in a models file):
#    from ..database import db
#    from your_orm import Mapped, mapped_column
#
#    class User(db.Model):
#        __tablename__ = "users"
#        id: Mapped[int] = mapped_column(primary_key=True)
#        name: Mapped[str]
