# This env.py is generated by your-orm.
# You can edit this file for advanced migration scenarios.

import asyncio
from logging.config import fileConfig

from sqlalchemy.ext.asyncio import create_async_engine
from alembic import context

# --- This is the most important part! ---
# The 'your-orm migrate init' command dynamically inserts the correct import path here.
from {db_object_module} import {db_object_name} as your_orm_db

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# --- Model Metadata ---
# This automatically links the migration tool to your application's models.
target_metadata = your_orm_db.metadata
db_url = your_orm_db.url

# Set the database URL from our central db object.
config.set_main_option("sqlalchemy.url", str(db_url))


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    context.configure(
        url=str(db_url),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection):
    """The synchronous callback that Alembic will run."""
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations():
    """The core async migration logic."""
    connectable = create_async_engine(str(db_url))

    async with connectable.connect() as connection:
        # Run the actual migrations within a synchronous, thread-safe context.
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    # We use asyncio.run to bridge the sync Alembic command with our async setup.
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
